//! Initial system configuration generated by the installer (WS11-03.8).
//!
//! Captures the first-boot decisions the installer collects — hostname,
//! timezone, locale, keymap, the primary user, and whether networking is on —
//! validates them, and serialises them to a deterministic `key = value`
//! document that the config store (WS17-01) reads on first boot. Serialisation
//! round-trips through [`InitialConfig::parse`].

use alloc::{
    collections::BTreeMap,
    string::{String, ToString},
};

/// Why an initial config was rejected or failed to parse.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigError {
    /// The hostname is not a valid RFC-1123 label.
    InvalidHostname,
    /// The primary username is not a valid login name.
    InvalidUsername,
    /// A serialised line was not `key = value`.
    MalformedLine,
    /// A required key was absent when parsing.
    MissingKey,
}

/// The initial system configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitialConfig {
    /// System hostname (RFC-1123 label).
    pub hostname: String,
    /// IANA timezone (e.g. `Europe/Rome`).
    pub timezone: String,
    /// Locale (e.g. `en_US.UTF-8`).
    pub locale: String,
    /// Console/keyboard layout (e.g. `us`).
    pub keymap: String,
    /// The primary (first) user account name.
    pub primary_user: String,
    /// Whether networking is enabled at first boot.
    pub enable_networking: bool,
}

/// Whether `name` is a valid RFC-1123 hostname label: 1..=63 chars of
/// `[a-z0-9-]`, not starting or ending with a hyphen.
#[must_use]
pub fn is_valid_hostname(name: &str) -> bool {
    let bytes = name.as_bytes();
    if bytes.is_empty() || bytes.len() > 63 {
        return false;
    }
    if bytes.first() == Some(&b'-') || bytes.last() == Some(&b'-') {
        return false;
    }
    bytes
        .iter()
        .all(|&b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

/// Whether `name` is a valid login name: 1..=32 chars of `[a-z0-9_-]` starting
/// with a lowercase letter or underscore (matching `nexacore-auth`).
#[must_use]
pub fn is_valid_username(name: &str) -> bool {
    let bytes = name.as_bytes();
    if bytes.is_empty() || bytes.len() > 32 {
        return false;
    }
    let first_ok = matches!(bytes.first(), Some(&b) if b.is_ascii_lowercase() || b == b'_');
    first_ok
        && bytes
            .iter()
            .all(|&b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_' || b == b'-')
}

impl InitialConfig {
    /// Validate hostname and username.
    ///
    /// # Errors
    /// [`ConfigError::InvalidHostname`] / [`ConfigError::InvalidUsername`].
    pub fn validate(&self) -> Result<(), ConfigError> {
        if !is_valid_hostname(&self.hostname) {
            return Err(ConfigError::InvalidHostname);
        }
        if !is_valid_username(&self.primary_user) {
            return Err(ConfigError::InvalidUsername);
        }
        Ok(())
    }

    /// Serialise to a deterministic `key = value` document (keys sorted).
    ///
    /// # Errors
    /// Propagates [`InitialConfig::validate`].
    pub fn serialize(&self) -> Result<String, ConfigError> {
        self.validate()?;
        let fields = [
            (
                "enable_networking",
                bool_str(self.enable_networking).to_string(),
            ),
            ("hostname", self.hostname.clone()),
            ("keymap", self.keymap.clone()),
            ("locale", self.locale.clone()),
            ("primary_user", self.primary_user.clone()),
            ("timezone", self.timezone.clone()),
        ];
        let mut out = String::new();
        for (key, value) in fields {
            out.push_str(key);
            out.push_str(" = ");
            out.push_str(&value);
            out.push('\n');
        }
        Ok(out)
    }

    /// Parse a `key = value` document back into a config, validating it.
    ///
    /// # Errors
    /// [`ConfigError::MalformedLine`] for a line without `=`,
    /// [`ConfigError::MissingKey`] if a field is absent, or a validation error.
    pub fn parse(doc: &str) -> Result<Self, ConfigError> {
        let mut map: BTreeMap<&str, &str> = BTreeMap::new();
        for line in doc.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            let (key, value) = line.split_once('=').ok_or(ConfigError::MalformedLine)?;
            map.insert(key.trim(), value.trim());
        }
        let get = |k: &str| map.get(k).copied().ok_or(ConfigError::MissingKey);
        let config = Self {
            hostname: get("hostname")?.to_string(),
            timezone: get("timezone")?.to_string(),
            locale: get("locale")?.to_string(),
            keymap: get("keymap")?.to_string(),
            primary_user: get("primary_user")?.to_string(),
            enable_networking: get("enable_networking")? == "true",
        };
        config.validate()?;
        Ok(config)
    }
}

fn bool_str(b: bool) -> &'static str {
    if b { "true" } else { "false" }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> InitialConfig {
        InitialConfig {
            hostname: "nexacore-01".to_string(),
            timezone: "Europe/Rome".to_string(),
            locale: "en_US.UTF-8".to_string(),
            keymap: "us".to_string(),
            primary_user: "matteo".to_string(),
            enable_networking: true,
        }
    }

    #[test]
    fn valid_config_round_trips_through_serialisation() {
        let cfg = sample();
        let doc = cfg.serialize().unwrap();
        assert_eq!(InitialConfig::parse(&doc).unwrap(), cfg);
        // Deterministic: keys sorted, so serialisation is stable.
        assert!(doc.starts_with("enable_networking = true\n"));
        assert!(doc.contains("hostname = nexacore-01\n"));
    }

    #[test]
    fn rejects_bad_hostname_and_username() {
        assert!(!is_valid_hostname("-bad"));
        assert!(!is_valid_hostname("Bad_Host"));
        assert!(!is_valid_hostname(""));
        assert!(is_valid_hostname("host-1"));

        let mut cfg = sample();
        cfg.hostname = "Invalid_Host".to_string();
        assert_eq!(cfg.validate(), Err(ConfigError::InvalidHostname));
        let mut cfg = sample();
        cfg.primary_user = "1root".to_string();
        assert_eq!(cfg.serialize(), Err(ConfigError::InvalidUsername));
    }

    #[test]
    fn parse_reports_malformed_and_missing() {
        assert_eq!(
            InitialConfig::parse("hostname host\n"),
            Err(ConfigError::MalformedLine)
        );
        assert_eq!(
            InitialConfig::parse("hostname = h\n"),
            Err(ConfigError::MissingKey)
        );
    }
}
